on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install gox for cross-compilation
        run: go install github.com/mitchellh/gox@latest
      - name: Get release notes
        id: release-notes
        run: |
          go mod download golang.org/x/tools
          go run ./script/issue-command/main.go set-output \
            --name=body \
            "$(go run ./script/release-changelog/main.go)"
      - name: Build cross-platform binaries
        run: make dist
      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract tag name without refs/tags/
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --notes "${{ steps.release-notes.outputs.body }}" \
            --verify-tag
          
          # Upload all dist files
          gh release upload "$TAG_NAME" dist/direnv.*
